name: scSpatial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - scanpy
  - napari
  - nomkl
  - pip
  - pip:
    - scconnect
    - git+https://github.com/linnarsson-lab/BoneFight.git@8c1ec1f
    - git+https://github.com/linnarsson-lab/loompy.git@master
    - cellpose[all]